<a href="https://colab.research.google.com/github/tewei0328/game/blob/master/array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
import numpy as np

In [2]:
a = np.arange(10)

In [3]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
b = np.arange(0,10,1)

In [13]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
c = np.linspace(0,10,10)

In [11]:
c

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [18]:
d = tf.Variable(tf.random.normal([10]))

In [19]:
d

<tf.Variable 'Variable:0' shape=(10,) dtype=float32, numpy=
array([ 0.1298654 ,  0.27026832,  0.17545797, -0.9235603 , -1.7902874 ,
       -0.62055814, -0.6553199 ,  1.0593334 , -0.19447647,  0.65204036],
      dtype=float32)>

In [21]:
e = tf.Variable(tf.zeros([10]))

In [22]:
e

<tf.Variable 'Variable:0' shape=(10,) dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>

In [24]:
f=tf.Variable(a)

In [25]:
f

<tf.Variable 'Variable:0' shape=(10,) dtype=int64, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])>